# Generated by Django 4.1.7 on 2023-03-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
            ],
        ),
    ]
